In [5]:
import pandas as pd
df = pd.read_csv("Dataset for Data Analytics week 3 - Sheet1.csv")
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [6]:
import sqlite3
conn = sqlite3.connect('orders.db')
df.to_sql('orders', conn, if_exists='replace', index=False)

1200

In [7]:
query1 = """
SELECT *
FROM orders;
"""

pd.read_sql(query1, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,None,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [8]:
query2 = """
SELECT OrderID, Product, Quantity, TotalPrice
FROM orders;
"""

pd.read_sql(query2, conn)

        OrderID  Product  Quantity  TotalPrice
0     ORD200000  Monitor         5     2853.10
1     ORD200001    Phone         2      302.70
2     ORD200002   Tablet         5     2753.40
3     ORD200003    Chair         1      273.19
4     ORD200004  Printer         4     2504.04
...         ...      ...       ...         ...
1195  ORD201195     Desk         1      107.04
1196  ORD201196  Monitor         2     1325.06
1197  ORD201197   Tablet         2      873.68
1198  ORD201198    Chair         4     1050.08
1199  ORD201199   Tablet         4     2242.32

[1200 rows x 4 columns]

In [9]:
query3 = """
SELECT *
FROM orders
WHERE TotalPrice > 2000;
"""

pd.read_sql(query3, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
2,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
3,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52
4,ORD200010,2023-12-29,C43443,Tablet,5,625.97,333 Main St,Credit Card,Returned,TRK98859248,9,WINTER15,Instagram,3129.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,ORD201155,2023-08-13,C41478,Printer,4,534.57,667 Main St,Credit Card,Delivered,TRK62068126,6,FREESHIP,Facebook,2138.28
176,ORD201156,2023-07-19,C20512,Laptop,4,690.78,980 Main St,Credit Card,Shipped,TRK98234737,9,None,Referral,2763.12
177,ORD201171,2023-08-28,C39911,Phone,4,518.40,699 Main St,Credit Card,Delivered,TRK80431998,7,SAVE10,Facebook,2073.60
178,ORD201179,2023-01-08,C84630,Laptop,5,518.55,907 Main St,Credit Card,Cancelled,TRK48054997,6,WINTER15,Instagram,2592.75
179,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [10]:
query4= """
SELECT *
FROM orders
WHERE OrderStatus = 'Delivered';
"""

pd.read_sql(query4, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
1,ORD200015,2023-07-17,C39416,Printer,1,473.96,942 Main St,Cash,Delivered,TRK54930938,3,None,Google,473.96
2,ORD200021,2024-11-17,C99023,Monitor,4,342.95,569 Main St,Cash,Delivered,TRK52646983,6,None,Google,1371.80
3,ORD200024,2024-10-30,C17470,Laptop,2,230.95,956 Main St,Online,Delivered,TRK28775057,3,WINTER15,Referral,461.90
4,ORD200025,2024-07-24,C42577,Monitor,1,399.98,709 Main St,Debit Card,Delivered,TRK69423327,3,WINTER15,Email,399.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,ORD201166,2023-07-31,C95568,Chair,3,324.47,971 Main St,Cash,Delivered,TRK37075292,4,WINTER15,Email,973.41
227,ORD201168,2023-04-08,C89559,Laptop,2,331.42,297 Main St,Credit Card,Delivered,TRK82838108,6,WINTER15,Google,662.84
228,ORD201171,2023-08-28,C39911,Phone,4,518.40,699 Main St,Credit Card,Delivered,TRK80431998,7,SAVE10,Facebook,2073.60
229,ORD201187,2024-03-13,C26340,Desk,2,184.60,562 Main St,Gift Card,Delivered,TRK59962703,7,WINTER15,Email,369.20
230,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68

In [11]:
query5 = """
SELECT *
FROM orders
WHERE PaymentMethod = 'Online';
"""

pd.read_sql(query5, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
1,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
2,ORD200011,2024-02-17,C93861,Monitor,3,49.14,831 Main St,Online,Returned,TRK48234646,7,SAVE10,Email,147.42
3,ORD200022,2023-01-29,C34416,Monitor,2,49.62,633 Main St,Online,Pending,TRK75937350,2,SAVE10,Google,99.24
4,ORD200024,2024-10-30,C17470,Laptop,2,230.95,956 Main St,Online,Delivered,TRK28775057,3,WINTER15,Referral,461.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,ORD201173,2024-10-04,C82921,Monitor,1,208.36,703 Main St,Online,Shipped,TRK31079911,4,FREESHIP,Email,208.36
254,ORD201181,2023-07-27,C70246,Desk,3,158.74,293 Main St,Online,Pending,TRK45708320,7,FREESHIP,Instagram,476.22
255,ORD201192,2024-02-28,C72007,Chair,3,432.85,999 Main St,Online,Pending,TRK16240916,4,None,Instagram,1298.55
256,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,None,Facebook,1325.06
257,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68

In [12]:
query6 = """
SELECT OrderID, Product, TotalPrice
FROM orders
ORDER BY TotalPrice DESC;
"""

pd.read_sql(query6, conn)

        OrderID  Product  TotalPrice
0     ORD200789   Tablet     3456.40
1     ORD201122  Monitor     3390.95
2     ORD200632   Laptop     3390.80
3     ORD200469    Chair     3384.90
4     ORD200328   Tablet     3370.20
...         ...      ...         ...
1195  ORD200336   Laptop       18.20
1196  ORD200542   Tablet       17.98
1197  ORD200240   Tablet       17.24
1198  ORD200863    Phone       14.06
1199  ORD201161    Phone       11.39

[1200 rows x 3 columns]

In [13]:
query7 = """
SELECT OrderID, Product, TotalPrice
FROM orders
ORDER BY TotalPrice ASC;
"""

pd.read_sql(query7, conn)

        OrderID  Product  TotalPrice
0     ORD201161    Phone       11.39
1     ORD200863    Phone       14.06
2     ORD200240   Tablet       17.24
3     ORD200542   Tablet       17.98
4     ORD200336   Laptop       18.20
...         ...      ...         ...
1195  ORD200328   Tablet     3370.20
1196  ORD200469    Chair     3384.90
1197  ORD200632   Laptop     3390.80
1198  ORD201122  Monitor     3390.95
1199  ORD200789   Tablet     3456.40

[1200 rows x 3 columns]

In [14]:
query8 = """
SELECT COUNT(*) AS Total_Orders
FROM orders;
"""

pd.read_sql(query8, conn)

   Total_Orders
0          1200

In [15]:
query9 = """
SELECT SUM(TotalPrice) AS Total_Revenue
FROM orders;
"""

pd.read_sql(query9, conn)

   Total_Revenue
0     1264761.96

In [16]:
query10 = """
SELECT AVG(TotalPrice) AS Average_Order_Value
FROM orders;
"""

pd.read_sql(query10, conn)

   Average_Order_Value
0            1053.9683

In [17]:
query11 = """
SELECT Product,
       COUNT(*) AS Number_of_Orders
FROM orders
GROUP BY Product
ORDER BY Number_of_Orders DESC;
"""

pd.read_sql(query11, conn)

   Product  Number_of_Orders
0  Printer               181
1   Tablet               179
2    Chair               178
3   Laptop               173
4     Desk               170
5  Monitor               163
6    Phone               156

In [18]:
query12 = """
SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY Product
ORDER BY Revenue DESC;
"""

pd.read_sql(query12, conn)

   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39

In [19]:
query13 = """
SELECT PaymentMethod,
       COUNT(*) AS Orders
FROM orders
GROUP BY PaymentMethod;
"""

pd.read_sql(query13, conn)

  PaymentMethod  Orders
0          Cash     246
1   Credit Card     234
2    Debit Card     232
3     Gift Card     230
4        Online     258

In [20]:
query14 = """
SELECT PaymentMethod,
       SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY PaymentMethod
ORDER BY Revenue DESC;
"""

pd.read_sql(query14, conn)

  PaymentMethod    Revenue
0   Credit Card  263847.63
1        Online  262442.94
2          Cash  259786.29
3     Gift Card  246323.92
4    Debit Card  232361.18

In [21]:
query15 = """
SELECT OrderStatus,
       COUNT(*) AS Orders
FROM orders
GROUP BY OrderStatus
ORDER BY Orders DESC;
"""

pd.read_sql(query15, conn)

  OrderStatus  Orders
0   Cancelled     250
1    Returned     247
2     Pending     237
3     Shipped     235
4   Delivered     231

In [22]:
query16 = """
SELECT ReferralSource,
       SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY ReferralSource
ORDER BY Revenue DESC;
"""

pd.read_sql(query16, conn)

  ReferralSource    Revenue
0      Instagram  275285.45
1          Email  261808.55
2         Google  250441.48
3       Facebook  250410.90
4       Referral  226815.58

In [23]:
query17 = """
SELECT Product,
       AVG(TotalPrice) AS Avg_Order_Value
FROM orders
GROUP BY Product
ORDER BY Avg_Order_Value DESC;
"""

pd.read_sql(query17, conn)

   Product  Avg_Order_Value
0   Laptop      1110.558150
1    Chair      1098.989382
2  Printer      1080.732652
3  Monitor      1077.616012
4   Tablet      1042.284637
5     Desk       985.058412
6    Phone       972.579423

In [24]:
query18 = """
SELECT OrderID,
       Product,
       TotalPrice
FROM orders
ORDER BY TotalPrice DESC
LIMIT 5;
"""

pd.read_sql(query18, conn)

     OrderID  Product  TotalPrice
0  ORD200789   Tablet     3456.40
1  ORD201122  Monitor     3390.95
2  ORD200632   Laptop     3390.80
3  ORD200469    Chair     3384.90
4  ORD200328   Tablet     3370.20

In [25]:
query19 = """
SELECT COUNT(*) AS Coupon_Users
FROM orders
WHERE CouponCode IS NOT NULL;
"""

pd.read_sql(query19, conn)

   Coupon_Users
0           891

In [26]:
query20 = """
SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY Product
HAVING SUM(TotalPrice) > 150000
ORDER BY Revenue DESC;
"""

pd.read_sql(query20, conn)

   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39